source 'https://rubygems.org'

gem 'berkshelf', '~> 7.0'
gem 'chef-dk', '~> 4.7'
gem 'chefspec', '~> 9.2'
gem 'cookstyle', '~> 6.8'
gem 'kitchen-inspec', '~> 1.3'
gem 'rake', '~> 13.0'
gem 'stove', '~> 7.1'
gem 'test-kitchen', '~> 2.4'
gem 'kitchen-dokken', '~> 2.9'
